org: ilperol
app: todo
service: todo-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins:
        - '*' 
      allowedHeaders:
        - '*'
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
      allowCredentials: false
  environment:
    TODOS_TABLE: TodosTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}"

functions:
  createTodo:
    handler: handler.createTodo
    events:
      - httpApi:
          path: /todos
          method: post
  getTodos:
    handler: handler.getTodos
    events:
      - httpApi:
          path: /todos
          method: get
  updateTodo:
    handler: handler.updateTodo
    events:
      - httpApi:
          path: /todos/{id}
          method: put
  deleteTodo:
    handler: handler.deleteTodo
    events:
      - httpApi:
          path: /todos/{id}
          method: delete

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodosTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
